version: "3.3"

volumes:
  grafana-storage:
  prom-storage:

services:
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - prom-storage:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: memorablepassword
      GF_INSTALL_PLUGINS: marcusolsson-csv-datasource
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    depends_on:
      - prometheus
    ports:
      - 3000:3000

  dht:
    image: lbry/dht-bootstrap:latest
    command: --metrics_port 7777
    restart: unless-stopped
    network_mode: "host"
    #ports:
    #  - 4444:4444/udp

#  node-exporter:
#    image: prom/node-exporter:latest
#    container_name: monitoring_node_exporter
#    restart: unless-stopped
#    volumes:
#      - "/:/host:ro,rslave"
#    command:
#      - "--path.rootfs=/host"
#    pid: host
#    #network_mode: host
#    expose: [9100]
