{
 "title": "LBRY",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "TODO",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Metrics\n\n- Percent of all published data hosted\n- Desktop app retention\n- Desktop app WAU\n- Blockchain metrics? # claims, # channels, TVL"
   }
  },
  { "title": "Key Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 }, "options": { "content": "\n# Blockchain" } },
  {
   "title": "Public Blockchain Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "schema": [
      { "name": "address", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Public lbcd Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "schema": [
      { "name": "user_agent", "type": "string" },
      { "name": "address", "type": "string" }
     ]
    }
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 5, "w": 3, "x": 0, "y": 14 }, "options": { "content": "# Data" } },
  { "title": "DHT Nodes (estimated)", "type": "timeseries", "gridPos": { "h": 5, "w": 4, "x": 3, "y": 14 } },
  { "title": "Total Data Hosted (estimated)", "type": "timeseries", "gridPos": { "h": 5, "w": 4, "x": 7, "y": 14 } },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 }, "options": { "content": "# Hubs" } },
  { "title": "Hubs", "type": "timeseries", "gridPos": { "h": 5, "w": 4, "x": 3, "y": 19 } },
  {
   "title": "Countries with Hubs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 19 },
   "targets": [
    {}
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 5, "w": 3, "x": 0, "y": 24 }, "options": { "content": "# Apps" } },
  {
   "title": "Apps with 10k+ DAU",
   "type": "stat",
   "description": "- LBRY Desktop\n- Odysee",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "2" }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Blocks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lbcd_blocks" }
   ]
  },
  {
   "title": "Countries with Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "schema": [
      { "name": "country", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Public Nodes",
   "type": "table",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 35 },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "schema": [
      { "name": "address", "type": "string" },
      { "name": "user_agent", "type": "string" },
      { "name": "country", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Nodes Map",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 45 },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "schema": [
      { "name": "address", "type": "string" },
      { "name": "country", "type": "string" }
     ]
    }
   ]
  },
  { "title": "Data Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "DHT Node Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dht_node_known_peers", "legendFormat": "known peers" }
   ]
  }
 ]
}