global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1

scrape_configs:

#- job_name: prometheus
#  honor_timestamps: true
#  metrics_path: /metrics
#  scheme: http
#  static_configs:
#  - targets:
#    - localhost:9090
#    - node-exporter:9100

#- job_name: grafana
#  metrics_path: /metrics
#  scheme: http
#  static_configs:
#  - targets:
#    - localhost:3000

- job_name: dht
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:7777

- job_name: dht_crawler
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:8080

- job_name: lbcd
  metrics_path: /
  scheme: http
  scrape_interval: 60s
  static_configs:
  - targets:
    - host.docker.internal:2114
