{
 "title": "DHT",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "% of reachable nodes, last 1h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "dht_crawler_node_reachable_hosts/dht_crawler_node_unique_total_hosts"
    }
   ]
  },
  {
   "title": "Requests received, per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(dht_node_received_request_total[5m])"
    }
   ]
  },
  {
   "title": "Total hosts, history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "dht_crawler_node_history_total_hosts"
    }
   ]
  },
  {
   "title": "Requests sent per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(dht_node_request_sent_total[5m])"
    }
   ]
  },
  {
   "title": "Pending hosts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "dht_crawler_node_pending_hosts" }
   ]
  },
  {
   "title": "Average routing table size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(dht_crawler_node_connections_found)"
    }
   ]
  },
  {
   "title": "Checked, last 1h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "dht_crawler_node_unique_total_hosts"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(dht_crawler_node_host_latency)"
    }
   ]
  },
  {
   "title": "Reachable hosts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "dht_crawler_node_reachable_hosts"
    }
   ]
  },
  {
   "title": "Hosts with errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "dht_crawler_node_error_hosts{instance=\"sdk.lbry.tech:7070\"}"
    }
   ]
  },
  {
   "title": "Reachable peers (1h)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select count(distinct address) from peer where latency > 0 and last_check > datetime('now', '-1 hour')",
     "rawQueryText": "select count(distinct address) from peer where latency > 0 and last_check > datetime('now', '-1 hour')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Recently seen peers (1h)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select count(*) from peer where last_seen > datetime('now', '-1 hour')",
     "rawQueryText": "select count(*) from peer where last_seen > datetime('now', '-1 hour')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Total sessions (full history)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select count(*) from peer",
     "rawQueryText": "select count(*) from peer",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Pending check",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select count(*) from peer where last_seen > datetime('now', '-1 hour') and (last_check < datetime('now', '-1 hour') or last_check is NULL)",
     "rawQueryText": "select count(*) from peer where last_seen > datetime('now', '-1 hour') and (last_check < datetime('now', '-1 hour') or last_check is NULL)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Reachable",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "queryText": "select latency/1000000, * from geoip join peer on geoip.peer_id=peer.peer_id where latency>0 and last_check > datetime('now', '-1 hour')",
     "rawQueryText": "select latency/1000000, * from geoip join peer on geoip.peer_id=peer.peer_id where latency>0 and last_check > datetime('now', '-1 hour')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Heatmap 24h",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "queryText": "select lat, long, address, case when latency is null then 9999 else latency/1000000 end as latency, peer.* from geoip join peer on peer.peer_id = geoip.peer_id where peer.last_check > datetime('now', '-1 day')",
     "rawQueryText": "select lat, long, address, case when latency is null then 9999 else latency/1000000 end as latency, peer.* from geoip join peer on peer.peer_id = geoip.peer_id where peer.last_check > datetime('now', '-1 day')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}