{
 "title": "LBRY",
 "time": { "from": "now-14d", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "TODO",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "- Desktop app retention / WAU\n- Hubs: how many, what jurisdictions?\n- Blockchain metrics? # claims, # channels, TVL"
   }
  },
  { "title": "Key Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 }, "options": { "content": "\n# Blockchain" } },
  {
   "title": "Public Blockchain Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "schema": [
      { "name": "address", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Public lbcd Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "schema": [
      { "name": "user_agent", "type": "string" },
      { "name": "address", "type": "string" }
     ]
    }
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 }, "options": { "content": "# Data" } },
  {
   "title": "DHT Nodes (estimated)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dht_crawler_node_unique_total_hosts"
    }
   ]
  },
  {
   "title": "Downloadable streams",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dht_crawler_node_working_streams_total / dht_crawler_node_probed_streams_total"
    }
   ]
  },
  {
   "title": "DHT Network Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dht_crawler_node_unique_total_hosts",
     "legendFormat": "Known"
    },
    {
     "expr": "dht_crawler_node_reachable_hosts",
     "legendFormat": "Reachable"
    }
   ]
  },
  {
   "title": "Total Data Hosted (estimated)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(dht_crawler_node_announced_streams_total[1h]) / rate(dht_crawler_node_probed_streams_total[1h])",
     "legendFormat": "Announced (1h)"
    },
    {
     "expr": "dht_crawler_node_working_streams_total / dht_crawler_node_probed_streams_total",
     "legendFormat": "Reachable"
    },
    {
     "expr": "dht_crawler_node_announced_streams_total / dht_crawler_node_probed_streams_total",
     "legendFormat": "Announced"
    },
    {
     "expr": "rate(dht_crawler_node_working_streams_total[1h]) / rate(dht_crawler_node_probed_streams_total[1h])",
     "legendFormat": "Reachable (1h)"
    }
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 5, "w": 3, "x": 0, "y": 27 }, "options": { "content": "# Hubs" } },
  { "title": "Hubs", "type": "timeseries", "gridPos": { "h": 5, "w": 4, "x": 3, "y": 27 } },
  {
   "title": "Countries with Hubs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 27 },
   "targets": [
    {}
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 5, "w": 3, "x": 0, "y": 32 }, "options": { "content": "# Apps" } },
  {
   "title": "Apps with 10k+ DAU",
   "type": "stat",
   "description": "- LBRY Desktop\n- Odysee",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "2" }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Blocks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lbcd_blocks" }
   ]
  },
  {
   "title": "Countries with Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "schema": [
      { "name": "country", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Public Nodes",
   "type": "table",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 43 },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "schema": [
      { "name": "address", "type": "string" },
      { "name": "user_agent", "type": "string" },
      { "name": "country", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Nodes Map",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 53 },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "schema": [
      { "name": "address", "type": "string" },
      { "name": "country", "type": "string" }
     ]
    }
   ]
  },
  { "title": "Data Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "DHT Node Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dht_node_peers_in_routing_table",
     "legendFormat": "known peers"
    }
   ]
  },
  {
   "title": "DHT Announcing Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dht_node_storing_peers", "legendFormat": "known peers" }
   ]
  },
  {
   "title": "DHT Total Stored Blobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dht_node_stored_blobs", "legendFormat": "known peers" }
   ]
  },
  {
   "title": "DHT Peers estimated from old method",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dht_node_peer_x_bit_colliding) * 256",
     "legendFormat": "known peers"
    }
   ]
  }
 ]
}