{
 "title": "Madiator.com Tracker",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Blockchain Nodes Map",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "columns": [
      { "selector": "country", "text": "country", "type": "string" }
     ],
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "source": "url",
     "type": "csv",
     "url": "https://nodes.madiator.com/static/data.csv",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "title": "DHT Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Blob Stored",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dht_node_blobs_stored{}" }
   ]
  },
  {
   "title": "Known Peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dht_node_known_peers{}" }
   ]
  },
  { "title": "HUB Tracker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Active Clients",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wallet_server_session_count{}", "legendFormat": "{{version}} " }
   ]
  },
  {
   "title": "Send transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wallet_server_requests_count_total{method=\"blockchain.transaction.broadcast\"})"
    }
   ]
  },
  {
   "title": "HUB Blocks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wallet_server_block_count{}" }
   ]
  },
  {
   "title": "LBRY Blockchain Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "columns": [
      { "selector": "address", "text": "Address", "type": "string" },
      { "selector": "port", "text": "Port", "type": "string" },
      { "selector": "user_agent", "text": "Version", "type": "string" },
      { "selector": "last_height", "text": "Last height", "type": "number" },
      { "selector": "address_type", "text": "Address type", "type": "string" },
      { "selector": "is_active", "text": "Active", "type": "string" },
      { "selector": "last_seen", "text": "Last Seen", "type": "timestamp_epoch_s" },
      { "selector": "country", "text": "Country", "type": "string" }
     ],
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "source": "url",
     "type": "csv",
     "url": "https://nodes.madiator.com/static/data.csv",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } }
 ]
}